# Generated by Django 6.1 on 2026-08-12 10:17

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(blank=True, max_length=64, null=True)),
                ('class_text', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=64, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('portal_student_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='PortalSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=16)),
                ('entity', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
            ],
            options={
                'db_table': 'portal_sync_log',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.CharField(default='', max_length=64)),
                ('academic_year', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student')], default='student', max_length=16)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('student', models.OneToOneField(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login', to='core.student')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('student', models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.student')),
                ('centroid', models.BinaryField()),
                ('dim', models.IntegerField()),
                ('sample_count', models.IntegerField(default=0)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'face_embeddings',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.schoolclass')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.schoolclass')),
            ],
            options={
                'db_table': 'enrollments',
                'unique_together': {('student', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('attendance_day', models.CharField(blank=True, max_length=16, null=True)),
                ('marked_by', models.ForeignKey(blank=True, db_column='marked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.student')),
                ('school_class', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolclass')),
                ('subject', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
            ],
            options={
                'db_table': 'attendance',
                'indexes': [models.Index(fields=['student', 'school_class', 'subject', 'timestamp'], name='attendance_student_57fb15_idx'), models.Index(fields=['school_class', 'subject', 'timestamp'], name='attendance_class_i_52ce46_idx'), models.Index(fields=['student', 'school_class', 'subject', 'attendance_day'], name='attendance_student_539094_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, default=core.models.now_iso, null=True)),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_assignments',
                'unique_together': {('user', 'school_class', 'subject')},
            },
        ),
    ]
