# Generated by Django 6.1 on 2026-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
