# Generated by Django 6.1 on 2026-08-26 08:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=64)),
                ('reg_no', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=300)),
                ('temp_image_dir', models.TextField(blank=True, null=True)),
                ('face_sample_count', models.IntegerField(default=0)),
                ('invite_code_used', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('csv_match_status', models.CharField(blank=True, max_length=16, null=True)),
                ('csv_match_detail', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.TextField(default=core.models.now_iso)),
                ('reviewed_at', models.TextField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_registrations', to='core.schoolclass')),
            ],
            options={
                'db_table': 'pending_registrations',
                'indexes': [models.Index(fields=['status'], name='pending_reg_status_f57615_idx'), models.Index(fields=['submitted_at'], name='pending_reg_submitt_fa96bb_idx')],
            },
        ),
    ]
