# Generated by Django 6.1 on 2026-08-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pending_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('mentor', 'mentor'), ('student', 'student')], default='student', max_length=16),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
