# Generated by Django 6.1 on 2026-09-17 05:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_geofencing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='checked_in_at',
            field=models.TextField(default=core.models.now_iso),
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='created_at',
            field=models.TextField(blank=True, default=core.models.now_iso, null=True),
        ),
    ]
